name: "Nette Tester"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test83:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
      php: "8.3"

  test82:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
      php: "8.2"

  test81_low:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
      php: "8.1"
      composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
